### ISSUE TITLE
Wrong accented characters in Romanian city names (cedillas instead of commas)

### ISSUE THREAD

**Issue by icflorescu** [amplifiedhq/countries-atlas#14]
Hello,

I just discovered a common error regarding the city names in my country/language.
The wrong accented characters are used in Romanian city names, as following:
- `ş` instead of `ș`
- 'ţ' instead of 'ț'
...and their corresponding uppercase variants.

See explanation and wiki links below:

The [T-cedilla](https://en.wikipedia.org/wiki/%C5%A2) and [S-cedilla](https://en.wikipedia.org/wiki/%C5%9E) characters are actually part of the [Gagauz](https://en.wikipedia.org/wiki/Gagauz_alphabet), [Dobrujan Tatar](https://en.wikipedia.org/wiki/Dobrujan_Tatar_alphabet) and probably other Turkish alphabets, while the correct characters used by the Romanian language are [T-comma](https://en.wikipedia.org/wiki/%C8%9A) and [S-comma](https://en.wikipedia.org/wiki/%C8%98).

Although the correct Romanian characters were introduced in Unicode 3.0, they were not supported in initial versions of Windows XP. While the old cedilla versions are still used in outdated systems, the **correct** characters used in modern systems are comma-based. 

I'll come up with a PR to fix this in a few minutes.

Thanks for taking the time and effort to build this cool library!

**Comment by hendurhance** [comment]
Thank you so much for identifying this issue and providing a fix!  I will merge your PR right away.
